services:
  readsb-main:
    build: ./readsb
    restart: unless-stopped
    environment:
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
      - READSB_DEVICE=0
      - READSB_GAIN=-10
    entrypoint: ./readsb/main.sh
    volumes:
    - "/run/readsb/:/run/readsb/"
    devices:
    - "/dev/bus/usb/:/dev/bus/usb/"
