services:
  readsb-main:
    build: ./readsb
    restart: unless-stopped
    environment:
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
      - READSB_DEVICE=1
      - READSB_GAIN=-10
    expose:
    - "30001:30001"
    - "30002:30002"
    - "30003:30002"
    - "30004:30004"
    - "30005:30005"
    - "30104:30104"
    command: sh -c ./main.sh
    volumes:
    - "/run/readsb/:/run/readsb/"
    - "./readsb/main.sh:/run/readsb/main.sh"
    - "/usr/share/zoneinfo/Europe/Berlin:/etc/localtime"
    devices:
    - "/dev/bus/usb/:/dev/bus/usb/"

  readsb-second:
    build: ./readsb
    restart: unless-stopped
    environment:
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
      - READSB_DEVICE=0
      - READSB_GAIN=-10
    command: sh -c ./second.sh
    volumes:
    - "./readsb/second.sh:/run/readsb/second.sh"
    - "/usr/share/zoneinfo/Europe/Berlin:/etc/localtime"
    devices:
    - "/dev/bus/usb/:/dev/bus/usb/"
