volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true

services:
  # Caddy
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - 443:443/udp
      - 443:443
      - 80:80
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - /usr/local/share/tar1090/html/:/usr/local/share/tar1090/html/
      - /run/readsb/:/run/readsb/
      - /run/tar1090/:/run/tar1090/
      - caddy_data:/data
      - caddy_config:/config

  # Node_Exporter
  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    restart: unless-stopped
    ports:
      - 9100:9100
    environment:
      - TZ=${TZ}
    command:
      - --path.rootfs=/host
      - --collector.textfile.directory=/run/readsb/
    pid: host
    volumes:
      - /:/host:ro,rslave
      - /run/readsb/:/run/readsb/:ro

  # Server every readsb-antenna-X container sends data to
  readsb-server:
    container_name: readsb-server
    build: ./build/readsb
    restart: unless-stopped
    entrypoint: /entrypoints/readsb-server.sh
    environment:
      - TZ=${TZ}
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
    ports:
    - 30001:30001
    - 30002:30002
    - 30003:30003
    - 30004:30004
    - 30005:30005
    - 30104:30104
    volumes:
    - /run/readsb/:/run/readsb/

  # Antenna
  readsb-antenna:
    container_name: readsb-antenna
    build: ./build/readsb
    restart: unless-stopped
    depends_on:
      - readsb-server
    entrypoint: /entrypoints/readsb-antenna.sh
    environment:
      - TZ=${TZ}
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
      - READSB_DEVICE=1
      - READSB_GAIN=40
      - READSB_BEAST_OUT=${READSB_BEAST_OUT}
    devices:
    - "/dev/bus/usb/001/004:/dev/bus/usb/001/004"

  # 2th antenna
  #readsb-antenna-2:
  #  container_name: readsb-antenna-2
  #  build: ./build/readsb
  #  restart: unless-stopped
  #  environment:
  #    - READSB_LAT=${LAT}
  #    - READSB_LON=${LON}
  #    - READSB_DEVICE=0
  #    - READSB_GAIN=20
  #  devices:
  #  - "/dev/bus/usb/001/004:/dev/bus/usb/001/004"

  # FEEDER
  readsb-feed:
    container_name: readsb-feed
    build: ./build/readsb
    restart: unless-stopped
    entrypoint: /entrypoints/readsb-feed.sh
    environment:
      - TZ=${TZ}
      - READSB_LAT=${LAT}
      - READSB_LON=${LON}
      - READSB_FEED=${READSB_FEED}
      - READSB_BEAST_IN=${READSB_BEAST_IN}
    volumes:
      - ./uuid:/script/uuid

  # FR24FEED
  fr24feed:
    container_name: fr24feed
    build: ./build/fr24feed
    restart: unless-stopped
    depends_on:
      - readsb-server
    volumes:
      - "./config/fr24feed.ini:/etc/fr24feed.ini"

  ###### MLAT Feeder

  # ADSBLOL MLAT
  adsblol-mlat:
    container_name: adsblol-mlat
    build: ./build/mlat-client
    restart: unless-stopped
    depends_on:
      - readsb-server
    environment:
      - TZ=${TZ}
      - MLAT_LAT=${LAT}
      - MLAT_LON=${LON}
      - MLAT_ALT=${ALT}
      - MLAT_USER=${MLAT_USER}
      - MLAT_INPUT=${MLAT_INPUT}
      - MLAT_RESULT=${MLAT_RESULT}
      - MLAT_SERVER=${ADSBLOL_MLAT}

  # ADSBX MLAT
  adsbx-mlat:
    container_name: adsbx-mlat
    build: ./build/mlat-client
    restart: unless-stopped
    depends_on:
      - readsb-server
    environment:
      - TZ=${TZ}
      - MLAT_LAT=${LAT}
      - MLAT_LON=${LON}
      - MLAT_ALT=${ALT}
      - MLAT_USER=${MLAT_USER}
      - MLAT_INPUT=${MLAT_INPUT}
      - MLAT_RESULT=${MLAT_RESULT}
      - MLAT_SERVER=${ADSBX_MLAT}

  # ADSBFI MLAT
  adsbfi-mlat:
    container_name: adsbfi-mlat
    build: ./build/mlat-client
    restart: unless-stopped
    depends_on:
      - readsb-server
    environment:
      - TZ=${TZ}
      - MLAT_LAT=${LAT}
      - MLAT_LON=${LON}
      - MLAT_ALT=${ALT}
      - MLAT_USER=${MLAT_USER}
      - MLAT_INPUT=${MLAT_INPUT}
      - MLAT_RESULT=${MLAT_RESULT}
      - MLAT_SERVER=${ADSBFI_MLAT}

  # ADSBONE MLAT
  adsbone-mlat:
    container_name: adsbone-mlat
    build: ./build/mlat-client
    restart: unless-stopped
    depends_on:
      - readsb-server
    environment:
      - TZ=${TZ}
      - MLAT_LAT=${LAT}
      - MLAT_LON=${LON}
      - MLAT_ALT=${ALT}
      - MLAT_USER=${MLAT_USER}
      - MLAT_INPUT=${MLAT_INPUT}
      - MLAT_RESULT=${MLAT_RESULT}
      - MLAT_SERVER=${ADSBONE_MLAT}

  # PLANESP MLAT
  planesp-mlat:
    container_name: planesp-mlat
    build: ./build/mlat-client
    restart: unless-stopped
    depends_on:
      - readsb-server
    environment:
      - TZ=${TZ}
      - MLAT_LAT=${LAT}
      - MLAT_LON=${LON}
      - MLAT_ALT=${ALT}
      - MLAT_USER=${MLAT_USER}
      - MLAT_INPUT=${MLAT_INPUT}
      - MLAT_RESULT=${MLAT_RESULT}
      - MLAT_SERVER=${PLANESP_MLAT}

  # Acarddec
#  acarsdec:
#    container_name: acarsdec
#    build: ./build/acarsdec
#    restart: unless-stopped
#    devices:
#    - "/dev/bus/usb/001/004:/dev/bus/usb/001/004"
